# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/HP/.vscode/ro-puf/PUF_VIV.srcs/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'puf_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/.vscode/ro-puf/PUF_VIV.gen/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'puf_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/HP/.vscode/ro-puf/PUF_VIV.gen/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'puf_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/HP/.vscode/ro-puf/PUF_VIV.srcs/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'puf_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/.vscode/ro-puf/PUF_VIV.gen/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'puf_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/HP/.vscode/ro-puf/PUF_VIV.gen/sources_1/bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'puf_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
