# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/puf_bd/puf_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd || ORIG_REF_NAME==puf_bd} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_processing_system7_0_0/puf_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_processing_system7_0_0 || ORIG_REF_NAME==puf_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_axi_gpio_0_1/puf_bd_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_axi_gpio_0_1 || ORIG_REF_NAME==puf_bd_axi_gpio_0_1} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_axi_gpio_1_1/puf_bd_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_axi_gpio_1_1 || ORIG_REF_NAME==puf_bd_axi_gpio_1_1} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_axi_smc_0/puf_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_axi_smc_0 || ORIG_REF_NAME==puf_bd_axi_smc_0} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_rst_ps7_0_50M_0/puf_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==puf_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/puf_bd/ip/puf_bd_puf_top_0_0/puf_bd_puf_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==puf_bd_puf_top_0_0 || ORIG_REF_NAME==puf_bd_puf_top_0_0} -quiet] -quiet

# XDC: c:/Users/HP/.vscode/ro-puf/PUF_VIV.gen/sources_1/bd/puf_bd/puf_bd_ooc.xdc
